title: Portfolio Test
author: Claudie Larouche
email: claudielarouche@gmail.com
lang: "en"
remote_theme: claudielarouche/portfolio-theme
plugins:
  - jekyll-remote-theme

baseurl: "/portfolio-test"

plugins:
  - jekyll-feed

# Tell Jekyll about your projects collection:
collections:
  projects:
    output: true     # so each project generates its own page

# Auto-apply your project layout to each file:
defaults:
  - scope:
      path: ""       # all files
      type: "projects"
    values:
      layout: project

  # Every post (in _posts/) uses layout: post
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post